version: '3'

services:
  gateway:
    image: gateway
    command: rocketChatMobilePushGateway --logtostderr=1
    restart: unless-stopped
    volumes:
      - ./mycerts:/certs
    ports:
      - 80:11000